### ISSUE TITLE
BLECon.js里面的第14.写入功能代码中的传入的e是什么数据？

### ISSUE THREAD

**Issue by deskol** [menglin1997/BLEConn#1]
因为我也是第一次接触这个蓝牙连接，不太理解这里的逻辑，所以请教一下，
还有循环中for (var i = 0;i < e.length; i += 20)  i+=20是表示什么意思？

![a2f6ea8c0535b86ffb5ad0049438bc4](https://user-images.githubusercontent.com/61148688/94354919-3519e400-00b2-11eb-98ac-5711163a471f.png)

**Comment by menglin1997** [comment]
发送字节的长度&nbsp;&nbsp;
模块一次性只能接收到20字节，所以这里以20字节为长度 作了一个分包操作
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "menglin1997/BLEConn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月27日(星期天) 中午11:14
收件人:&nbsp;"menglin1997/BLEConn"<BLEConn@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[menglin1997/BLEConn] BLECon.js里面的第14.写入功能代码中的传入的e是什么数据？ (#1)





 
因为我也是第一次接触这个蓝牙连接，不太理解这里的逻辑，所以请教一下，
 还有循环中for (var i = 0;i < e.length; i += 20)  i+=20是表示什么意思？

**Comment by menglin1997** [comment]
发送字节的长度&nbsp;&nbsp;
模块一次性只能接收到20字节，所以这里将20字节为基础 做了一个分包操作

**Comment by deskol** [comment]
好的，谢谢指点

**Comment by menglin1997** [comment]
不客气



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "de1921"<notifications@github.com&gt;; 
发送时间: 2020年9月27日(星期天) 中午1:36
收件人: "menglin1997/BLEConn"<BLEConn@noreply.github.com&gt;; 
抄送: "梦里花开"<1351931529@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [menglin1997/BLEConn] BLECon.js里面的第14.写入功能代码中的传入的e是什么数据？ (#1)





 
好的，谢谢指点
