### ISSUE TITLE
微信小程序直接提示 hexToArrayBuffer is not defined

### ISSUE THREAD

**Issue by work4blue** [menglin1997/BLEConn#2]
VM97:1 MiniProgramError
ReferenceError: hexToArrayBuffer is not defined
ReferenceError: hexToArrayBuffer is not defined
at hexToArrayBuffer (uni-app:///utils/socket/BLEConn.js:608:1)
at  (uni-app:///utils/socket/BLEConn.js:618:1)
at call (null:91:1)

```
// 其他转换方法
//16进制字符串转 ArrayBuffer 
hexToArrayBuffer = (hex) => {. //<--指向这里错误
return new Uint8Array(
	hex.match(/[\da-f]{2}/gi).map((byte) => {
	return parseInt(byte, 16)
	})
).buffer
}
  
//ArrayBuffer类型数据转为16进制字符串
bufToHex = (buffer) => {
return Array.prototype.map.call(new Uint8Array(buffer), (x) => ('00' + x.toString(16)).slice(-2)).join('')
}
```

**Comment by shengbinxu** [comment]
<img width="1238" alt="image" src="https://github.com/menglin1997/BLEConn/assets/3232275/35d456c7-cb38-4997-9084-a4d1642264e3">
这几行代码注释掉就能启动了，也不报错了

**Comment by menglin1997** [comment]
该问题已修复 可以看本次提交https://github.com/menglin1997/BLEConn/commit/3f2361eef4b0aded8cb745559a3b4916babb4109

或者听取楼上意见 注释那两部分代码
