### ISSUE TITLE
运行到安卓手机报错，运行到小程序无法加载

### ISSUE THREAD

**Issue by JinxuanChen03** [menglin1997/BLEConn#5]
用HBuilderX在华为手机上运行，出现以下错误
[Vue warn]: You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.

**Comment by JinxuanChen03** [comment]
问题解决，是因为login.vue中首行少了一个<template>

**Comment by JinxuanChen03** [comment]
问题解决，是因为login.vue中首行少了一个<template>标签

**Comment by JinxuanChen03** [comment]
问题解决，是因为login.vue中首行少了一个template标签，加上就可以运行了。看了一下原代码template标签是正常的，可能因为莫名其妙的原因我自己把标签删了没发现

**Comment by menglin1997** [comment]
> 问题解决，是因为login.vue中首行少了一个template标签，加上就可以运行了。看了一下原代码template标签是正常的，可能因为莫名其妙的原因我自己把标签删了没发现

发现有些模块不需要分包也是可以的 抽空我把更新一下代码
